language: erlang
otp_release:
    - 17.3
services:
    - redis-server
install:
    - make build
    - make cert
    - "git clone -b enhancement https://github.com/gbour/nyamuk.git tests/nyamuk"
script:
    - ./.travis-run.sh
notifications:
    email: "travis-wave@bour.cc"
