sudo: required
dist: trusty
group: edge

language: erlang
otp_release:
    - 17.3
    - 17.5
    - 18.3
    - 19.0

services:
    - redis-server

addons:
    apt:
        packages:
            - python-redis
            - python-twisted-web

install:
    # get deps, compile code, generates config according to choosed environment
    - DEBUG=1 make env=travis all
    # create autosigned certificate (single & chained w/ CA)
    - make cert && make chain-cert
    # need to enable TLSv1 as python2.7 do not support TLS >= 1.1
    - sed -ie "s/{versions, .*\}/{versions, ['tlsv1', 'tlsv1.1', 'tlsv1.2']}/g" .wave.travis.config
    # nyamuk is a python MQTT client used for blackbox tests
    - pip install --user websocket-client
    - "git clone -b enhancement https://github.com/gbour/nyamuk.git tests/nyamuk"
    - "git clone https://github.com/gbour/twotp.git tests/twotp"
    - "git clone https://github.com/gbour/python_etf.git tests/etf"
    - pip install --user -r tests/etf/test_requirements.txt
    - "git clone https://github.com/gbour/apache-log-parser.git tests/logparser"
    - pip install --user -r tests/logparser/requirements.txt
    - "git clone https://github.com/gbour/paho.mqtt.testing tests/paho"

before_script:
    - kerl list installations
    # starting wave broker
    - "erl -pa `find -L _build/travis -name ebin` -s wave_app -config .wave.travis.config -noinput -name 'wave@127.0.0.1' -setcookie wave&"
    - PID=$!
    # wait until broker started
    - sleep 10

script:
    - make dialyze
    # set context (auth, acl) for paho tests
    - PYTHONPATH=tests/twotp tests/paho_setup init
    - python3 tests/paho/interoperability/client_test.py --iterations 3 -zs 2> /tmp/wave.paho.log
    - PYTHONPATH=tests/twotp tests/paho_setup cleanup
    #
    - make DEBUG=/tmp/wave.tests.log WAVELOGS=/tmp/wave.travis.log env=travis test

after_script:
    - kill -HUP $PID
    - cat /tmp/wave.tests.log
    - cat /tmp/wave.paho.log
    - cat /tmp/wave.travis.log

notifications:
    email: "travis-wave@bour.cc"
